let shopItemsData = [
    {
      id: 1,
      name: "Casual Shirt",
      img: "images/img-1.jpg",
      desc: "Men's Solid Slim Fit Cotton Casual Shirt with Spread Collar & Full Sleeves (Also Available in Plus Size)",
      price: 67,
    },
    {
      id: 2,
      name: "Office Shirt",
      img: "images/img-2.jpg",
      desc: "Men's Solid Slim Fit Cotton office Shirt with Spread Collar & Full Sleeves (Also Available in Plus Size)",
      price: 107,
    },
    {
      id: 3,
      name: "T Shirt",
      img: "images/img-3.jpg",
      desc: "Men's Solid Slim Fit Cotton Casual t Shirt with Spread Collar & Full Sleeves (Also Available in Plus Size)",
      price: 342,
    },
    {
      id: 4,
      name: "Mens Suit",
      img: "images/img-4.jpg",
      desc: "Men's Solid Slim Fit 3 piece suit (Also Available in Plus Size)",
      price: 323,
    },
    {
      id: 5,
      name: "Mens Tie",
      img: "images/img-5.png",
      desc: "Men's Solid Slim Fit tie (Also Available in Plus Size)",
      price: 225,
    },
    {
      id: 6,
      name: "Casual shoes",
      img: "images/img-6.png",
      desc:"Mens Shoes (Also Available in Plus Size)",
      price: 210,
    },
    {
      id: 7,
      name: "black suit",
      img: "images/img-7.png",
      desc: "Men's Solid Blck suit (Also Available in Plus Size)",
      price: 450,
    },
    {
      id: 8,
      name: "polo shirt",
      img: "images/img-8.png",
      desc: "Men's Solid Slim Fit Polo Shirt with Spread Collar & Full Sleeves (Also Available in Plus Size)",
      price: 75,
    },
    {
      name: "denim shirt",
      id: 9,
      img: "images/img-9.png",
      desc: "Men's Solid Slim Fit Denim Shirt with Spread Collar & Full Sleeves (Also Available in Plus Size)",
      price: 115,
    },
    {
      id: 10,
      name: "denim pants",
      img: "images/img-10.png",
      desc: "Men's Solid Pants (Also Available in Plus Size)",
      price: 120,
    },
    {
      id: 11,
      name: "basic cap",
      img: "images/img-11.png",
      desc: "Men's Solid Slim Fit Cotton Casual Shirt with Spread Collar & Full Sleeves (Also Available in Plus Size)",
      price: 35,
    },
    {
      id: 12,
      name: "leather boots",
      img: "images/img-12.png",
      desc: "Men's Solid Boots (Also Available in Plus Size)",
      price: 350,
    },
  ];